"""Command line entry point.

Three commands:
  seed  -- build a knowledge base from a customer's existing e2e suite
  run   -- execute a QA run against a live app and report
  demo  -- the whole pipeline end to end against the bundled buggy shop app

`demo` is the one to read first. It stands the entire loop up in-process and shows
the bot grading an application whose defects we planted on purpose.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fastapi.testclient import TestClient

from qabot.drivers.browser import BrowserDriver
from qabot.drivers.http import HttpDriver
from qabot.llm import default_provider
from qabot.models import Expectation, Provenance
from qabot.reporter import exit_code, render_markdown
from qabot.runner import run as run_qa
from qabot.seeder import seed_knowledge_base
from qabot.store import KBStore
from qabot.testgen import emit_tests


def _synthetic_diff(source_root: Path) -> str:
    """Build a unified diff touching the checkout handler.

    Generated by locating the function in the source rather than hardcoding line
    numbers, so the demo keeps working when demo/app.py changes.
    """
    app_path = source_root / "demo" / "app.py"
    lines = app_path.read_text().splitlines()
    # Anchor on the route path, not the handler name: the path is part of the app's
    # published contract, the Python function name is an implementation detail.
    target = next(
        (i for i, line in enumerate(lines, start=1) if '"/checkout/submit"' in line),
        None,
    )
    if target is None:
        raise SystemExit(f"could not find the /checkout/submit route in {app_path}")
    # Point the hunk a couple of lines in, so it overlaps the handler body rather
    # than just its decorator.
    target = min(target + 2, len(lines))
    return (
        "diff --git a/demo/app.py b/demo/app.py\n"
        "--- a/demo/app.py\n"
        "+++ b/demo/app.py\n"
        f"@@ -{target},3 +{target},4 @@\n"
        f" {lines[target - 1]}\n"
        "+    # (pretend this PR changed payment error handling)\n"
        f" {lines[target] if target < len(lines) else ''}\n"
    )


def _confirm_expired_card_expectation(kb) -> None:
    """Stand in for the async curator loop.

    In production a human answers an open question in the dashboard and the answer
    is written back as a `human_confirmed` expectation. Here we do that inline so
    the demo can show the full severity ladder: this is the one expectation allowed
    to be reported as a BUG.
    """
    workflow = next((w for w in kb.workflows if "expired" in w.id), None)
    if workflow is None:
        raise SystemExit(
            "demo expects a seeded workflow mentioning 'expired'; none found. "
            f"seeded ids: {[w.id for w in kb.workflows]}"
        )
    # Bind it to the checkout step. An expectation without a step_index is graded
    # against the last response in the workflow, which here would be a trailing
    # GET /cart -- correct verdict, wrong evidence.
    checkout_step = next(
        (
            i
            for i, step in enumerate(workflow.steps)
            if step.hint and step.hint.get("path") == "/checkout/submit"
        ),
        None,
    )
    if checkout_step is None:
        raise SystemExit(
            f"demo expects workflow {workflow.id} to POST /checkout/submit; "
            f"steps were {[s.hint.get('path') if s.hint else None for s in workflow.steps]}"
        )
    workflow.expectations.append(
        Expectation(
            id=f"{workflow.id}_human1",
            statement="the error message identifies the card as expired",
            provenance=Provenance.HUMAN_CONFIRMED,
            confidence=0.95,
            check={"kind": "json_contains", "path": "message", "value": "expired"},
            step_index=checkout_step,
        )
    )


def cmd_seed(args: argparse.Namespace) -> int:
    kb = seed_knowledge_base(Path(args.e2e_dir), repo=args.repo)
    KBStore(Path(args.out)).save(kb)
    total_exp = sum(len(w.expectations) for w in kb.workflows)
    checked = sum(1 for w in kb.workflows for e in w.expectations if e.check)
    print(
        f"seeded {len(kb.workflows)} workflows, {total_exp} expectations "
        f"({checked} machine-checkable, {total_exp - checked} prose-only) -> {args.out}"
    )
    # What we could not read is the more important number, and it used to go unprinted.
    # A seed line reporting only its successes reads as "we understood your suite", which
    # is the same lie the run report is forbidden to tell about a truncated run.
    if kb.open_questions:
        calls = sum(len(q.candidates) for q in kb.open_questions)
        print(
            f"{calls} calls could not be classified as HTTP requests and were not seeded; "
            f"{len(kb.open_questions)} open questions in the knowledge base name them"
        )
    return 0


def _header_arg(raw: str) -> tuple[str, str]:
    """Parse one `--header 'Name: Value'`.

    Loud on anything malformed, because a header we silently dropped produces a run
    of 401s that reads as a broken application -- the most expensive way there is to
    find out about a typo.

    Deliberately mute about what was actually passed. A malformed credential is still
    a credential and argparse's error goes to a CI log, so the message describes the
    shape and never echoes the value. `ArgumentTypeError` is what makes that possible:
    raising `ValueError` here would have argparse print the offending string for us.
    """
    name, separator, value = raw.partition(":")
    if not separator or not name.strip() or not value.strip():
        raise argparse.ArgumentTypeError(
            "expected 'Name: Value', both halves non-empty (the value itself is not "
            "echoed here, since it is probably a credential)"
        )
    return name.strip(), value.strip()


def _cookie_arg(raw: str) -> tuple[str, str]:
    """Parse one `--cookie 'name=value'`. Same contract as `_header_arg`."""
    name, separator, value = raw.partition("=")
    if not separator or not name.strip() or not value.strip():
        raise argparse.ArgumentTypeError(
            "expected 'name=value', both halves non-empty (the value itself is not "
            "echoed here, since it is a session credential)"
        )
    return name.strip(), value.strip()


def cmd_run(args: argparse.Namespace) -> int:
    kb = KBStore(Path(args.kb)).snapshot()
    diff_text = sys.stdin.read() if args.diff == "-" else Path(args.diff).read_text()
    # A third-party app has no /reset endpoint. Opting out is the caller's decision,
    # and it costs them a stated limitation on the run rather than a silent one.
    #
    # Credentials come in already obtained: qabot does not log in. Duplicate names
    # collapse last-wins, which is what a caller repeating a flag to correct it means.
    driver = HttpDriver(
        base_url=args.base_url,
        reset_path=None if args.no_reset else "/reset",
        headers=dict(args.header or []),
        cookies=dict(args.cookie or []),
    )
    try:
        report = run_qa(
            kb=kb,
            driver=driver,
            source_root=Path(args.source_root),
            diff_text=diff_text,
            llm=default_provider(),
            budget=args.budget,
        )
    finally:
        driver.close()
    print(render_markdown(report))
    if args.emit_tests:
        out_dir = Path(args.emit_tests)
        out_dir.mkdir(parents=True, exist_ok=True)
        for filename, source in emit_tests(report).items():
            (out_dir / filename).write_text(source)
            print(f"wrote {out_dir / filename}", file=sys.stderr)
    return exit_code(report, blocking=args.blocking)


def cmd_demo(args: argparse.Namespace) -> int:
    from demo.app import create_app

    source_root = Path(args.source_root)
    kb = seed_knowledge_base(source_root / "demo" / "e2e", repo="demo/shop")
    _confirm_expired_card_expectation(kb)

    # starlette's TestClient is an httpx.Client subclass with a *synchronous* ASGI
    # transport. httpx's own ASGITransport is async-only, so it cannot back the
    # driver's sync interface.
    client = TestClient(create_app())
    driver = HttpDriver(base_url=str(client.base_url), client=client)
    try:
        report = run_qa(
            kb=kb,
            driver=driver,
            source_root=source_root,
            diff_text=_synthetic_diff(source_root),
            llm=default_provider(),
            budget=args.budget,
        )
    finally:
        driver.close()

    print(render_markdown(report))
    generated = emit_tests(report)
    if generated:
        print("\n" + "=" * 72)
        print("GENERATED REGRESSION TESTS (from verified expectations only)")
        print("=" * 72)
        for filename, source in generated.items():
            print(f"\n--- {filename} ---\n{source}")
    else:
        print("\n(no workflow passed cleanly, so no regression tests were generated)")

    if args.json_out:
        Path(args.json_out).write_text(json.dumps(report.model_dump(mode="json"), indent=2))
        print(f"\nrun report written to {args.json_out}", file=sys.stderr)
    return 0


def _diff_touching(source_root: Path, relative: str, marker: str) -> str:
    """A unified diff over the line where `marker` appears, so impact analysis has
    something real to select on."""
    path = source_root / relative
    lines = path.read_text().splitlines()
    target = next((i for i, line in enumerate(lines, start=1) if marker in line), None)
    if target is None:
        raise SystemExit(f"could not find {marker!r} in {path}")
    target = min(target + 2, len(lines))
    return (
        f"diff --git a/{relative} b/{relative}\n"
        f"--- a/{relative}\n"
        f"+++ b/{relative}\n"
        f"@@ -{target},3 +{target},4 @@\n"
        f" {lines[target - 1]}\n"
        "+    # (pretend this PR changed the checkout page)\n"
        f" {lines[target] if target < len(lines) else ''}\n"
    )


def cmd_demo_browser(args: argparse.Namespace) -> int:
    from playwright.sync_api import sync_playwright

    from demo.app import create_app
    from demo.server import serve
    from demo.workflows import browser_knowledge_base

    source_root = Path(args.source_root)
    kb = browser_knowledge_base()
    diff_text = _diff_touching(source_root, "demo/ui.py", "def ui_checkout")
    artifacts = Path(args.artifacts)

    with serve(create_app()) as base_url, sync_playwright() as pw:
        browser = pw.chromium.launch(headless=not args.headed)
        page = browser.new_page()
        driver = BrowserDriver(base_url=base_url, page=page, artifacts_dir=artifacts)
        try:
            report = run_qa(
                kb=kb,
                driver=driver,
                source_root=source_root,
                diff_text=diff_text,
                llm=default_provider(),
                budget=args.budget,
            )
        finally:
            driver.close()
            browser.close()

    print(render_markdown(report))
    generated = emit_tests(report)
    if generated:
        print("\n" + "=" * 72)
        print("GENERATED REGRESSION TESTS (from verified expectations only)")
        print("=" * 72)
        for filename, source in generated.items():
            print(f"\n--- {filename} ---\n{source}")
    print(f"\nscreenshots written to {artifacts}/", file=sys.stderr)
    return exit_code(report, blocking=args.blocking)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="qabot", description="QA bot prototype")
    sub = parser.add_subparsers(dest="command", required=True)

    p_seed = sub.add_parser("seed", help="build a knowledge base from an existing e2e suite")
    p_seed.add_argument("--e2e-dir", required=True)
    p_seed.add_argument("--repo", required=True)
    p_seed.add_argument("--out", default="kb.json")
    p_seed.set_defaults(func=cmd_seed)

    p_run = sub.add_parser("run", help="run QA against a live app")
    p_run.add_argument("--kb", required=True)
    p_run.add_argument("--base-url", required=True)
    p_run.add_argument("--source-root", default=".")
    p_run.add_argument("--diff", required=True, help="path to a unified diff, or - for stdin")
    p_run.add_argument("--budget", type=int, default=10)
    p_run.add_argument("--emit-tests", default=None, help="directory to write generated tests")
    p_run.add_argument("--blocking", action="store_true", help="exit 1 on bugs/regressions")
    p_run.add_argument(
        "--no-reset",
        action="store_true",
        help="the app has no POST /reset; run anyway and state the limitation in the report",
    )
    p_run.add_argument(
        "--header",
        action="append",
        type=_header_arg,
        metavar="'Name: Value'",
        help="header sent on every request, e.g. 'Authorization: Bearer ...'. Repeatable. "
        "Values are redacted from the report and from generated tests.",
    )
    p_run.add_argument(
        "--cookie",
        action="append",
        type=_cookie_arg,
        metavar="'name=value'",
        help="cookie sent on every request, e.g. a session cookie from a login you "
        "performed yourself. Repeatable. Never recorded in the report.",
    )
    p_run.set_defaults(func=cmd_run)

    p_demo = sub.add_parser("demo", help="end-to-end demo against the bundled buggy app")
    p_demo.add_argument("--source-root", default=".")
    p_demo.add_argument("--budget", type=int, default=10)
    p_demo.add_argument("--json-out", default=None)
    p_demo.set_defaults(func=cmd_demo)

    p_browser = sub.add_parser("demo-browser", help="end-to-end demo driven through a real browser")
    p_browser.add_argument("--source-root", default=".")
    p_browser.add_argument("--budget", type=int, default=10)
    p_browser.add_argument("--artifacts", default="qa-artifacts")
    p_browser.add_argument("--headed", action="store_true", help="watch the browser work")
    p_browser.add_argument("--blocking", action="store_true")
    p_browser.set_defaults(func=cmd_demo_browser)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
